version : '2'

services:
  mongodb24:
    container_name: phpmongo_mongo24
    image: mongo:2.4

  mongodb26:
    container_name: phpmongo_mongo26
    image: mongo:2.6

  mongodb30:
    container_name: phpmongo_mongo30
    image: mongo:3.0

  mongodb32:
    container_name: phpmongo_mongo32
    image: mongo:3.2

  mongodb33:
    container_name: phpmongo_mongo33
    image: mongo:3.3

  mongodb34:
    container_name: phpmongo_mongo34
    image: mongo:3.4

  mongodb36:
    container_name: phpmongo_mongo36
    image: mongo:3.6

  mongodb40:
    container_name: phpmongo_mongo40
    image: mongo:4.0

  mongodb41:
    container_name: phpmongo_mongo41
    image: mongo:4.1

  php70:
    image: php:7.0
    container_name: phpmongo_php70
    command: bash /phpmongo-source/docker/php/init.sh 1.5.3
    volumes:
      - ..:/phpmongo-source
      - /phpmongo-source/vendor
      - ./share:/share
    environment:
      PHP_IDE_CONFIG: "serverName=phpmongo"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
      RES_OPTIONS: "retrans:1 retry:1 timeout:1 attempts:1"

  php71:
    image: php:7.1
    container_name: phpmongo_php71
    command: bash /phpmongo-source/docker/php/init.sh 1.5.3
    volumes:
      - ..:/phpmongo-source
      - /phpmongo-source/vendor
      - ./share:/share
    environment:
      PHP_IDE_CONFIG: "serverName=phpmongo"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
      RES_OPTIONS: "retrans:1 retry:1 timeout:1 attempts:1"

  php72:
    image: php:7.2
    container_name: phpmongo_php72
    command: bash /phpmongo-source/docker/php/init.sh 1.5.3
    volumes:
      - ..:/phpmongo-source
      - /phpmongo-source/vendor
      - ./share:/share
    environment:
      PHP_IDE_CONFIG: "serverName=phpmongo"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
      RES_OPTIONS: "retrans:1 retry:1 timeout:1 attempts:1"

  php73:
    image: php:7.3-rc
    container_name: phpmongo_php73
    command: bash /phpmongo-source/docker/php/init.sh 1.5.3
    volumes:
      - ..:/phpmongo-source
      - /phpmongo-source/vendor
      - ./share:/share
    environment:
      PHP_IDE_CONFIG: "serverName=phpmongo"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
      RES_OPTIONS: "retrans:1 retry:1 timeout:1 attempts:1"
